name: Deploy pythonanywhere webapp

on: 
  push:
      branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Re-Deploy Pythonanywhere Django API
        uses: umuttopalak/pythonanywhere-deploy-action@v1.0.0
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.USERNAME }}
          api_token: ${{ secrets.API_TOKEN }}
          domain_name: ${{ secrets.DOMAIN_NAME }}
          console_id:  ${{ secrets.CONSOLE_ID }}
          virtual_env: ${{ secrets.VIRTUAL_ENV }}
          directory: ${{ secrets.DIRECTORY }}

